<option value="533">Adilabad, TL</option>
<option value="547">Agra, UP</option>
<option value="131">Ahmadabad (Ahmedabad), GJ</option>
<option value="331">Ahmadnagar (Ahmednagar), MH</option>
<option value="382">Aizawl, MZ</option>
<option value="455">Ajmer, RJ</option>
<option value="332">Akola, MH</option>
<option value="266">Alappuzha, KL</option>
<option value="548">Aligarh, UP</option>
<option value="281">Alirajpur, MP</option>
<option value="549">Allahabad, UP</option>
<option value="618">Almora, UK</option>
<option value="456">Alwar, RJ</option>
<option value="157">Ambala, HR</option>
<option value="550">Ambedkar Nagar, UP</option>
<option value="333">Amravati, MH</option>
<option value="132">Amreli, GJ</option>
<option value="435">Amritsar, PB</option>
<option value="551">Amroha (Jyotiba Phule Nagar), UP</option>
<option value="133">Anand, GJ</option>
<option value="4">Anantapur, AP</option>
<option value="190">Anantnag, JK</option>
<option value="17">Anjaw, AR</option>
<option value="401">Anugul (Angul), OR</option>
<option value="282">Anuppur, MP</option>
<option value="60">Araria, BR</option>
<option value="501">Ariyalur, TN</option>
<option value="61">Arwal, BR</option>
<option value="283">Ashoknagar, MP</option>
<option value="552">Auraiya, UP</option>
<option value="62">Aurangabad, BR</option>
<option value="334">Aurangabad, MH</option>
<option value="553">Azamgarh, UP</option>
<option value="191">Badgam, JK</option>
<option value="236">Bagalkot, KA</option>
<option value="619">Bageshwar, UK</option>
<option value="554">Baghpat, UP</option>
<option value="555">Bahraich, UP</option>
<option value="33">Baksa, AS</option>
<option value="284">Balaghat, MP</option>
<option value="402">Balangir, OR</option>
<option value="403">Baleshwar (Balasore), OR</option>
<option value="556">Ballia, UP</option>
<option value="557">Balrampur, UP</option>
<option value="134">Banas Kantha, GJ</option>
<option value="558">Banda, UP</option>
<option value="192">Bandipore (Bandipora), JK</option>
<option value="237">Bangalore, KA</option>
<option value="238">Bangalore Rural, KA</option>
<option value="63">Banka, BR</option>
<option value="631">Bankura, WB</option>
<option value="457">Banswara, RJ</option>
<option value="559">Bara Banki, UP</option>
<option value="193">Baramula (Baramulla), JK</option>
<option value="458">Baran, RJ</option>
<option value="632">Barddhaman (Burdwan), WB</option>
<option value="560">Bareilly, UP</option>
<option value="404">Bargarh, OR</option>
<option value="459">Barmer, RJ</option>
<option value="436">Barnala, PB</option>
<option value="34">Barpeta, AS</option>
<option value="285">Barwani, MP</option>
<option value="99">Bastar, CG</option>
<option value="561">Basti, UP</option>
<option value="437">Bathinda, PB</option>
<option value="405">Baudh (Boudh), OR</option>
<option value="64">Begusarai, BR</option>
<option value="239">Belgaum, KA</option>
<option value="240">Bellary, KA</option>
<option value="286">Betul, MP</option>
<option value="406">Bhadrak, OR</option>
<option value="65">Bhagalpur, BR</option>
<option value="335">Bhandara, MH</option>
<option value="460">Bharatpur, RJ</option>
<option value="135">Bharuch, GJ</option>
<option value="136">Bhavnagar, GJ</option>
<option value="461">Bhilwara, RJ</option>
<option value="287">Bhind, MP</option>
<option value="158">Bhiwani, HR</option>
<option value="66">Bhojpur, BR</option>
<option value="288">Bhopal, MP</option>
<option value="336">Bid (Beed), MH</option>
<option value="241">Bidar, KA</option>
<option value="100">Bijapur, CG</option>
<option value="242">Bijapur, KA</option>
<option value="562">Bijnor, UP</option>
<option value="462">Bikaner, RJ</option>
<option value="101">Bilaspur, CG</option>
<option value="178">Bilaspur, HP</option>
<option value="633">Birbhum, WB</option>
<option value="366">Bishnupur, MN</option>
<option value="212">Bokaro, JH</option>
<option value="35">Bongaigaon, AS</option>
<option value="563">Budaun, UP</option>
<option value="564">Bulandshahr, UP</option>
<option value="337">Buldana (Buldhana), MH</option>
<option value="463">Bundi, RJ</option>
<option value="289">Burhanpur, MP</option>
<option value="67">Buxar, BR</option>
<option value="36">Cachar, AS</option>
<option value="120">Central, DL</option>
<option value="243">Chamarajanagar, KA</option>
<option value="179">Chamba, HP</option>
<option value="620">Chamoli, UK</option>
<option value="621">Champawat, UK</option>
<option value="383">Champhai, MZ</option>
<option value="565">Chandauli, UP</option>
<option value="367">Chandel, MN</option>
<option value="98">Chandigarh, CH</option>
<option value="338">Chandrapur, MH</option>
<option value="18">Changlang, AR</option>
<option value="213">Chatra, JH</option>
<option value="502">Chennai, TN</option>
<option value="290">Chhatarpur, MP</option>
<option value="291">Chhindwara, MP</option>
<option value="244">Chikkaballapura (Chikballapur), KA</option>
<option value="245">Chikmagalur (Chikkamagaluru), KA</option>
<option value="37">Chirang, AS</option>
<option value="246">Chitradurga, KA</option>
<option value="566">Chitrakoot, UP</option>
<option value="464">Chittaurgarh (Chittorgarh), RJ</option>
<option value="5">Chittoor, AP</option>
<option value="368">Churachandpur, MN</option>
<option value="465">Churu, RJ</option>
<option value="503">Coimbatore, TN</option>
<option value="504">Cuddalore, TN</option>
<option value="407">Cuttack, OR</option>
<option value="117">Dadra & Nagar Haveli, DN</option>
<option value="102">Dakshin Bastar Dantewada, CG</option>
<option value="634">Dakshin Dinajpur, WB</option>
<option value="247">Dakshina Kannada, KA</option>
<option value="118">Daman, DD</option>
<option value="292">Damoh, MP</option>
<option value="68">Darbhanga, BR</option>
<option value="635">Darjiling (Darjeeling), WB</option>
<option value="38">Darrang, AS</option>
<option value="293">Datia, MP</option>
<option value="466">Dausa, RJ</option>
<option value="248">Davanagere, KA</option>
<option value="408">Debagarh, OR</option>
<option value="622">Dehradun, UK</option>
<option value="214">Deoghar, JH</option>
<option value="567">Deoria, UP</option>
<option value="294">Dewas, MP</option>
<option value="543">Dhalai, TR</option>
<option value="103">Dhamtari, CG</option>
<option value="215">Dhanbad, JH</option>
<option value="295">Dhar, MP</option>
<option value="505">Dharmapuri, TN</option>
<option value="249">Dharwad, KA</option>
<option value="467">Dhaulpur (Dholpur), RJ</option>
<option value="39">Dhemaji, AS</option>
<option value="409">Dhenkanal, OR</option>
<option value="40">Dhubri, AS</option>
<option value="339">Dhule, MH</option>
<option value="19">Dibang Valley, AR</option>
<option value="41">Dibrugarh, AS</option>
<option value="42">Dima Hasao, AS</option>
<option value="390">Dimapur, NL</option>
<option value="506">Dindigul, TN</option>
<option value="296">Dindori, MP</option>
<option value="119">Diu, DD</option>
<option value="194">Doda, JK</option>
<option value="137">Dohad (Dahod), GJ</option>
<option value="216">Dumka, JH</option>
<option value="468">Dungarpur, RJ</option>
<option value="104">Durg, CG</option>
<option value="121">East, DL</option>
<option value="375">East Garo Hills, ML</option>
<option value="6">East Godavari, AP</option>
<option value="20">East Kameng, AR</option>
<option value="376">East Khasi Hills, ML</option>
<option value="21">East Siang, AR</option>
<option value="488">East Sikkim, SK</option>
<option value="267">Ernakulam, KL</option>
<option value="507">Erode, TN</option>
<option value="568">Etah, UP</option>
<option value="569">Etawah, UP</option>
<option value="570">Faizabad, UP</option>
<option value="159">Faridabad, HR</option>
<option value="438">Faridkot, PB</option>
<option value="571">Farrukhabad, UP</option>
<option value="160">Fatehabad, HR</option>
<option value="439">Fatehgarh Sahib, PB</option>
<option value="572">Fatehpur, UP</option>
<option value="573">Firozabad, UP</option>
<option value="440">Firozpur, PB</option>
<option value="250">Gadag, KA</option>
<option value="340">Gadchiroli, MH</option>
<option value="410">Gajapati, OR</option>
<option value="195">Ganderbal, JK</option>
<option value="138">Gandhinagar, GJ</option>
<option value="469">Ganganagar (Sri Ganganagar), RJ</option>
<option value="411">Ganjam, OR</option>
<option value="217">Garhwa, JH</option>
<option value="623">Garhwal (Pauri Garhwal), UK</option>
<option value="574">Gautam Buddha Nagar, UP</option>
<option value="69">Gaya, BR</option>
<option value="575">Ghaziabad, UP</option>
<option value="576">Ghazipur, UP</option>
<option value="218">Giridih, JH</option>
<option value="43">Goalpara, AS</option>
<option value="219">Godda, JH</option>
<option value="44">Golaghat, AS</option>
<option value="577">Gonda, UP</option>
<option value="341">Gondiya (Gondia), MH</option>
<option value="70">Gopalganj, BR</option>
<option value="578">Gorakhpur, UP</option>
<option value="251">Gulbarga, KA</option>
<option value="220">Gumla, JH</option>
<option value="297">Guna, MP</option>
<option value="7">Guntur, AP</option>
<option value="441">Gurdaspur, PB</option>
<option value="161">Gurgaon, HR</option>
<option value="298">Gwalior, MP</option>
<option value="45">Hailakandi, AS</option>
<option value="579">Hamirpur, UP</option>
<option value="180">Hamirpur, HP</option>
<option value="470">Hanumangarh, RJ</option>
<option value="636">Haora (Howrah), WB</option>
<option value="299">Harda, MP</option>
<option value="580">Hardoi, UP</option>
<option value="624">Hardwar (Haridwar), UK</option>
<option value="252">Hassan, KA</option>
<option value="581">Hathras (Mahamaya Nagar), UP</option>
<option value="253">Haveri, KA</option>
<option value="221">Hazaribagh, JH</option>
<option value="342">Hingoli, MH</option>
<option value="162">Hisar, HR</option>
<option value="300">Hoshangabad, MP</option>
<option value="442">Hoshiarpur, PB</option>
<option value="637">Hugli (Hooghly), WB</option>
<option value="534">Hyderabad, TL</option>
<option value="268">Idukki, KL</option>
<option value="369">Imphal East, MN</option>
<option value="370">Imphal West, MN</option>
<option value="301">Indore, MP</option>
<option value="302">Jabalpur, MP</option>
<option value="412">Jagatsinghapur, OR</option>
<option value="377">Jaintia Hills, ML</option>
<option value="471">Jaipur, RJ</option>
<option value="472">Jaisalmer, RJ</option>
<option value="413">Jajapur, OR</option>
<option value="443">Jalandhar, PB</option>
<option value="582">Jalaun, UP</option>
<option value="343">Jalgaon, MH</option>
<option value="344">Jalna, MH</option>
<option value="473">Jalor (Jalore), RJ</option>
<option value="638">Jalpaiguri, WB</option>
<option value="196">Jammu, JK</option>
<option value="139">Jamnagar, GJ</option>
<option value="222">Jamtara, JH</option>
<option value="71">Jamui, BR</option>
<option value="105">Janjgir-Champa, CG</option>
<option value="106">Jashpur, CG</option>
<option value="583">Jaunpur, UP</option>
<option value="72">Jehanabad, BR</option>
<option value="303">Jhabua, MP</option>
<option value="163">Jhajjar, HR</option>
<option value="474">Jhalawar, RJ</option>
<option value="584">Jhansi, UP</option>
<option value="414">Jharsuguda, OR</option>
<option value="475">Jhunjhunu, RJ</option>
<option value="164">Jind, HR</option>
<option value="476">Jodhpur, RJ</option>
<option value="46">Jorhat, AS</option>
<option value="140">Junagadh, GJ</option>
<option value="107">Kabirdham (Kabeerdham), CG</option>
<option value="141">Kachchh, GJ</option>
<option value="73">Kaimur (Bhabua), BR</option>
<option value="165">Kaithal, HR</option>
<option value="415">Kalahandi, OR</option>
<option value="47">Kamrup, AS</option>
<option value="48">Kamrup Metropolitan, AS</option>
<option value="508">Kanchipuram (Kancheepuram), TN</option>
<option value="416">Kandhamal, OR</option>
<option value="181">Kangra, HP</option>
<option value="585">Kannauj, UP</option>
<option value="509">Kanniyakumari (Kanyakumari), TN</option>
<option value="269">Kannur, KL</option>
<option value="586">Kanpur Dehat, UP</option>
<option value="587">Kanpur Nagar, UP</option>
<option value="444">Kapurthala, PB</option>
<option value="431">Karaikal, PY</option>
<option value="477">Karauli, RJ</option>
<option value="49">Karbi Anglong, AS</option>
<option value="197">Kargil, JK</option>
<option value="50">Karimganj, AS</option>
<option value="535">Karimnagar, TL</option>
<option value="166">Karnal, HR</option>
<option value="510">Karur, TN</option>
<option value="270">Kasaragod, KL</option>
<option value="588">Kasganj (Kanshiram Nagar), UP</option>
<option value="198">Kathua, JK</option>
<option value="74">Katihar, BR</option>
<option value="304">Katni, MP</option>
<option value="589">Kaushambi, UP</option>
<option value="417">Kendrapara, OR</option>
<option value="418">Kendujhar, OR</option>
<option value="75">Khagaria, BR</option>
<option value="536">Khammam, TL</option>
<option value="305">Khandwa (East Nimar), MP</option>
<option value="306">Khargone (West Nimar), MP</option>
<option value="142">Kheda, GJ</option>
<option value="590">Kheri (Lakhimpur Kheri), UP</option>
<option value="419">Khordha, OR</option>
<option value="223">Khunti, JH</option>
<option value="182">Kinnaur, HP</option>
<option value="391">Kiphire, NL</option>
<option value="76">Kishanganj, BR</option>
<option value="199">Kishtwar, JK</option>
<option value="639">Koch Bihar (Cooch Behar), WB</option>
<option value="254">Kodagu, KA</option>
<option value="224">Kodarma (Koderma), JH</option>
<option value="392">Kohima, NL</option>
<option value="51">Kokrajhar, AS</option>
<option value="255">Kolar, KA</option>
<option value="384">Kolasib, MZ</option>
<option value="345">Kolhapur, MH</option>
<option value="640">Kolkata, WB</option>
<option value="271">Kollam, KL</option>
<option value="256">Koppal, KA</option>
<option value="420">Koraput, OR</option>
<option value="108">Korba, CG</option>
<option value="109">Koriya, CG</option>
<option value="478">Kota, RJ</option>
<option value="272">Kottayam, KL</option>
<option value="273">Kozhikode, KL</option>
<option value="8">Krishna, AP</option>
<option value="511">Krishnagiri, TN</option>
<option value="200">Kulgam, JK</option>
<option value="183">Kullu, HP</option>
<option value="201">Kupwara, JK</option>
<option value="9">Kurnool, AP</option>
<option value="167">Kurukshetra, HR</option>
<option value="22">Kurung Kumey, AR</option>
<option value="591">Kushinagar, UP</option>
<option value="184">Lahul & Spiti, HP</option>
<option value="52">Lakhimpur, AS</option>
<option value="77">Lakhisarai, BR</option>
<option value="280">Lakshadweep, LD</option>
<option value="592">Lalitpur, UP</option>
<option value="225">Latehar, JH</option>
<option value="346">Latur, MH</option>
<option value="385">Lawngtlai, MZ</option>
<option value="202">Leh (Ladakh), JK</option>
<option value="226">Lohardaga, JH</option>
<option value="23">Lohit, AR</option>
<option value="393">Longleng, NL</option>
<option value="24">Lower Dibang Valley, AR</option>
<option value="25">Lower Subansiri, AR</option>
<option value="593">Lucknow, UP</option>
<option value="445">Ludhiana, PB</option>
<option value="386">Lunglei, MZ</option>
<option value="78">Madhepura, BR</option>
<option value="79">Madhubani, BR</option>
<option value="512">Madurai, TN</option>
<option value="110">Mahasamund, CG</option>
<option value="537">Mahbubnagar, TL</option>
<option value="432">Mahe, PY</option>
<option value="168">Mahendragarh, HR</option>
<option value="143">Mahesana (Mehsana), GJ</option>
<option value="594">Mahoba, UP</option>
<option value="595">Mahrajganj (Maharajganj), UP</option>
<option value="596">Mainpuri, UP</option>
<option value="274">Malappuram, KL</option>
<option value="641">Maldah, WB</option>
<option value="421">Malkangiri, OR</option>
<option value="387">Mamit, MZ</option>
<option value="185">Mandi, HP</option>
<option value="307">Mandla, MP</option>
<option value="308">Mandsaur, MP</option>
<option value="257">Mandya, KA</option>
<option value="446">Mansa, PB</option>
<option value="597">Mathura, UP</option>
<option value="598">Mau, UP</option>
<option value="422">Mayurbhanj, OR</option>
<option value="538">Medak, TL</option>
<option value="599">Meerut, UP</option>
<option value="169">Mewat, HR</option>
<option value="600">Mirzapur, UP</option>
<option value="447">Moga, PB</option>
<option value="394">Mokokchung, NL</option>
<option value="395">Mon, NL</option>
<option value="601">Moradabad, UP</option>
<option value="309">Morena, MP</option>
<option value="53">Morigaon (Marigaon), AS</option>
<option value="448">Muktsar (Sri Muktsar Sahib), PB</option>
<option value="347">Mumbai, MH</option>
<option value="348">Mumbai Suburban, MH</option>
<option value="80">Munger, BR</option>
<option value="642">Murshidabad, WB</option>
<option value="602">Muzaffarnagar, UP</option>
<option value="81">Muzaffarpur, BR</option>
<option value="258">Mysore, KA</option>
<option value="423">Nabarangapur (Nabarangpur), OR</option>
<option value="643">Nadia, WB</option>
<option value="54">Nagaon, AS</option>
<option value="513">Nagapattinam, TN</option>
<option value="479">Nagaur, RJ</option>
<option value="349">Nagpur, MH</option>
<option value="625">Nainital, UK</option>
<option value="82">Nalanda, BR</option>
<option value="55">Nalbari, AS</option>
<option value="539">Nalgonda, TL</option>
<option value="514">Namakkal, TN</option>
<option value="350">Nanded, MH</option>
<option value="351">Nandurbar, MH</option>
<option value="111">Narayanpur, CG</option>
<option value="144">Narmada, GJ</option>
<option value="310">Narsimhapur (Narsinghpur), MP</option>
<option value="352">Nashik, MH</option>
<option value="145">Navsari, GJ</option>
<option value="83">Nawada, BR</option>
<option value="424">Nayagarh, OR</option>
<option value="311">Neemuch, MP</option>
<option value="122">New Delhi, DL</option>
<option value="1">Nicobar, AN</option>
<option value="540">Nizamabad, TL</option>
<option value="123">North, DL</option>
<option value="2">North & Middle Andaman, AN</option>
<option value="124">North East, DL</option>
<option value="129">North Goa, GA</option>
<option value="489">North Sikkim, SK</option>
<option value="544">North Tripura, TR</option>
<option value="644">North Twenty Four Parganas, WB</option>
<option value="125">North West, DL</option>
<option value="425">Nuapada, OR</option>
<option value="353">Osmanabad, MH</option>
<option value="227">Pakur, JH</option>
<option value="275">Palakkad, KL</option>
<option value="228">Palamu, JH</option>
<option value="480">Pali, RJ</option>
<option value="170">Palwal, HR</option>
<option value="146">Panch Mahals (Panchmahal), GJ</option>
<option value="171">Panchkula, HR</option>
<option value="172">Panipat, HR</option>
<option value="312">Panna, MP</option>
<option value="26">Papum Pare, AR</option>
<option value="354">Parbhani, MH</option>
<option value="645">Paschim Medinipur, WB</option>
<option value="84">Pashchim Champaran (West Champaran), BR</option>
<option value="229">Pashchimi Singhbhum (West Singhbhum), JH</option>
<option value="147">Patan, GJ</option>
<option value="276">Pathanamthitta, KL</option>
<option value="449">Patiala, PB</option>
<option value="85">Patna, BR</option>
<option value="515">Perambalur, TN</option>
<option value="396">Peren, NL</option>
<option value="397">Phek, NL</option>
<option value="603">Pilibhit, UP</option>
<option value="626">Pithoragarh, UK</option>
<option value="148">Porbandar, GJ</option>
<option value="10">Prakasam, AP</option>
<option value="604">Pratapgarh, UP</option>
<option value="481">Pratapgarh, RJ</option>
<option value="433">Puducherry (Pondicherry), PY</option>
<option value="516">Pudukkottai, TN</option>
<option value="203">Pulwama, JK</option>
<option value="204">Punch (Poonch), JK</option>
<option value="355">Pune, MH</option>
<option value="86">Purba Champaran (East Champaran), BR</option>
<option value="646">Purba Medinipur, WB</option>
<option value="230">Purbi Singhbhum (East Singhbhum), JH</option>
<option value="426">Puri, OR</option>
<option value="87">Purnia, BR</option>
<option value="647">Puruliya (Purulia), WB</option>
<option value="605">Rae Bareli, UP</option>
<option value="259">Raichur, KA</option>
<option value="356">Raigad, MH</option>
<option value="112">Raigarh, CG</option>
<option value="113">Raipur, CG</option>
<option value="313">Raisen, MP</option>
<option value="314">Rajgarh, MP</option>
<option value="149">Rajkot, GJ</option>
<option value="114">Rajnandgaon, CG</option>
<option value="205">Rajouri, JK</option>
<option value="482">Rajsamand, RJ</option>
<option value="260">Ramanagara, KA</option>
<option value="517">Ramanathapuram, TN</option>
<option value="206">Ramban, JK</option>
<option value="231">Ramgarh, JH</option>
<option value="606">Rampur, UP</option>
<option value="232">Ranchi, JH</option>
<option value="541">Rangareddy, TL</option>
<option value="315">Ratlam, MP</option>
<option value="357">Ratnagiri, MH</option>
<option value="427">Rayagada, OR</option>
<option value="207">Reasi, JK</option>
<option value="316">Rewa, MP</option>
<option value="173">Rewari, HR</option>
<option value="378">Ribhoi, ML</option>
<option value="174">Rohtak, HR</option>
<option value="88">Rohtas, BR</option>
<option value="627">Rudraprayag, UK</option>
<option value="450">Rupnagar, PB</option>
<option value="150">Sabar Kantha, GJ</option>
<option value="317">Sagar, MP</option>
<option value="607">Saharanpur, UP</option>
<option value="89">Saharsa, BR</option>
<option value="233">Sahibganj, JH</option>
<option value="451">Sahibzada Ajit Singh Nagar, PB</option>
<option value="388">Saiha, MZ</option>
<option value="518">Salem, TN</option>
<option value="90">Samastipur, BR</option>
<option value="208">Samba, JK</option>
<option value="428">Sambalpur, OR</option>
<option value="358">Sangli, MH</option>
<option value="452">Sangrur, PB</option>
<option value="608">Sant Kabir Nagar, UP</option>
<option value="609">Sant Ravidas Nagar (Bhadohi), UP</option>
<option value="234">Saraikela-Kharsawan, JH</option>
<option value="91">Saran, BR</option>
<option value="359">Satara, MH</option>
<option value="318">Satna, MP</option>
<option value="483">Sawai Madhopur, RJ</option>
<option value="319">Sehore, MP</option>
<option value="371">Senapati, MN</option>
<option value="320">Seoni, MP</option>
<option value="389">Serchhip, MZ</option>
<option value="321">Shahdol, MP</option>
<option value="453">Shahid Bhagat Singh Nagar, PB</option>
<option value="610">Shahjahanpur, UP</option>
<option value="322">Shajapur, MP</option>
<option value="92">Sheikhpura, BR</option>
<option value="93">Sheohar, BR</option>
<option value="323">Sheopur, MP</option>
<option value="186">Shimla, HP</option>
<option value="261">Shimoga, KA</option>
<option value="324">Shivpuri, MP</option>
<option value="611">Shrawasti (Shravasti), UP</option>
<option value="209">Shupiyan (Shopian), JK</option>
<option value="612">Siddharthnagar, UP</option>
<option value="325">Sidhi, MP</option>
<option value="484">Sikar, RJ</option>
<option value="235">Simdega, JH</option>
<option value="360">Sindhudurg, MH</option>
<option value="326">Singrauli, MP</option>
<option value="187">Sirmaur, HP</option>
<option value="485">Sirohi, RJ</option>
<option value="175">Sirsa, HR</option>
<option value="94">Sitamarhi, BR</option>
<option value="613">Sitapur, UP</option>
<option value="519">Sivaganga, TN</option>
<option value="56">Sivasagar, AS</option>
<option value="95">Siwan, BR</option>
<option value="188">Solan, HP</option>
<option value="361">Solapur, MH</option>
<option value="614">Sonbhadra, UP</option>
<option value="176">Sonipat, HR</option>
<option value="57">Sonitpur, AS</option>
<option value="126">South, DL</option>
<option value="3">South Andaman, AN</option>
<option value="379">South Garo Hills, ML</option>
<option value="130">South Goa, GA</option>
<option value="490">South Sikkim, SK</option>
<option value="545">South Tripura, TR</option>
<option value="648">South Twenty Four Parganas, WB</option>
<option value="127">South West, DL</option>
<option value="12">Sri Potti Sriramulu Nellore, AP</option>
<option value="11">Srikakulam, AP</option>
<option value="210">Srinagar, JK</option>
<option value="429">Subarnapur, OR</option>
<option value="615">Sultanpur, UP</option>
<option value="430">Sundargarh (Sundergarh), OR</option>
<option value="96">Supaul, BR</option>
<option value="151">Surat, GJ</option>
<option value="152">Surendranagar, GJ</option>
<option value="115">Surguja, CG</option>
<option value="372">Tamenglong, MN</option>
<option value="153">Tapi, GJ</option>
<option value="454">Tarn Taran, PB</option>
<option value="27">Tawang, AR</option>
<option value="628">Tehri Garhwal, UK</option>
<option value="362">Thane, MH</option>
<option value="520">Thanjavur, TN</option>
<option value="154">The Dangs, GJ</option>
<option value="522">The Nilgiris, TN</option>
<option value="521">Theni, TN</option>
<option value="523">Thiruvallur (Tiruvallur), TN</option>
<option value="277">Thiruvananthapuram, KL</option>
<option value="524">Thiruvarur (Tiruvarur), TN</option>
<option value="525">Thoothukkudi, TN</option>
<option value="373">Thoubal, MN</option>
<option value="278">Thrissur, KL</option>
<option value="327">Tikamgarh, MP</option>
<option value="58">Tinsukia, AS</option>
<option value="28">Tirap, AR</option>
<option value="526">Tiruchirappalli, TN</option>
<option value="527">Tirunelveli, TN</optit;n>
<option value="528">Tiruppur, TN</option>
<option value="529">Tiruvannamalai, TN</option>
<option value="486">Tonk, RJ</option>
<option value="398">Tuensang, NL</option>
<option value="262">Tumkur, KA</option>
<option value="487">Udaipur, RJ</option>
<option value="59">Udalguri, AS</option>
<option value="629">Udham Singh Nagar, UK</option>
<option value="211">Udhampur, JK</option>
<option value="263">Udupi, KA</option>
<option value="328">Ujjain, MP</option>
<option value="374">Ukhrul, MN</option>
<option value="329">Umaria, MP</option>
<option value="189">Una, HP</option>
<option value="616">Unnao, UP</option>
<option value="29">Upper Siang, AR</option>
<option value="30">Upper Subansiri, AR</option>
<option value="116">Uttar Bastar Kanker, CG</option>
<option value="649">Uttar Dinajpur, WB</option>
<option value="264">Uttara Kannada, KA</option>
<option value="630">Uttarkashi, UK</option>
<option value="155">Vadodara, GJ</option>
<option value="97">Vaishali, BR</option>
<option value="156">Valsad, GJ</option>
<option value="617">Varanasi, UP</option>
<option value="530">Vellore, TN</option>
<option value="330">Vidisha, MP</option>
<option value="531">Viluppuram, TN</option>
<option value="532">Virudhunagar, TN</option>
<option value="13">Visakhapatnam, AP</option>
<option value="14">Vizianagaram, AP</option>
<option value="542">Warangal, TL</option>
<option value="363">Wardha, MH</option>
<option value="364">Washim, MH</option>
<option value="279">Wayanad, KL</option>
<option value="128">West, DL</option>
<option value="380">West Garo Hills, ML</option>
<option value="15">West Godavari, AP</option>
<option value="31">West Kameng, AR</option>
<option value="381">West Khasi Hills, ML</option>
<option value="32">West Siang, AR</option>
<option value="491">West Sikkim, SK</option>
<option value="546">West Tripura, TR</option>
<option value="399">Wokha, NL</option>
<option value="16">Y.S.R. (Cuddapah), AP</option>
<option value="265">Yadgir, KA</option>
<option value="177">Yamunanagar, HR</option>
<option value="434">Yanam, PY</option>
<option value="365">Yavatmal, MH</option>
<option value="400">Zunheboto, NL</option>