<div class="cat_listing">

           <div class="page_heading">
            <h1> Online</h1>
        </div>
        <style type="text/css">
@media screen and (max-width: 640px) {
	.site-footer{display:none !important;}
	.bottom{display:none !important;}
	.order_history_track{display:none !important;}
	.mob_top_three_links{display:none !important;}
	.foot-bluebot-mobile{display:none !important;}
	.header_new_mob{background-color:#000000 !important;}
	.header_middle_bar{background-color:#000000 !important; border-top-color:#000000 !important;}
	#mobile_menu{display:none !important;}
	.mobile_header_right{display:none !important;}
	.box_search{display:none !important;}
	.header_middle_bar{display:none !important;}
	.ml_containermain{top:50px !important;}
}
</style>

<h1 style="text-align:center; font-size:18px; color: #0079a9;">Overview</h1>
<p><strong>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures to make the terms of this policy binding.</strong></p>
 <p>At WokBuy.com data protection is a matter of trust and your privacy is very important to us. We use your personal information only in the manner set out in this Privacy Policy. Please read this privacy policy to learn more about our information gathering and dissemination practices. </p>
 <p>The privacy practices of this statement apply to our services available under the domain and sub-domains of WokBuy.com (the "Site") and apply generally to our parent, affiliates, subsidiaries or joint venture websites. By visiting the Site you agree to be bound by the terms and conditions of this Privacy Policy. </p>
 <p>This Privacy Policy explains how WokBuy.com gathers personal information, classified as mandatory or optional as part of the normal operation of our services; and uses, discloses and protects such information through the Site.  This detailed privacy policy enables you to take informed decisions in dealings with us. Our parent, subsidiaries and joint ventures operate under similar privacy practices subject to the requirements of applicable law.</p>
 <p>By registering with WokBuy.com, you acknowledge your acceptance of the terms of this Privacy Policy, expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy and that any personal information provided by you through WokBuy.com is provided under a lawful contract. This Privacy Policy is incorporated into and subject to the terms of the User Agreement.
Note: Our privacy policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically.</p>

 <h4>Your Privacy</h4>
 <p>At WokBuy.com, we are extremely proud of our commitment to protect your privacy. We value your trust in us. We work hard to earn your confidence so that you can enthusiastically use our services and recommend your friends and family to participate in dealing with us. Please read the following policy to understand how your personal information will be treated as you make full use of our Site.</p>

 <h4>WokBuy.com Privacy Assurance</h4>
 <p>WokBuy.com promises that we will not sell or rent your personal information to third parties for their marketing purposes without your explicit consent. From time to time we may reveal general statistical information about our Web site and visitors, such as number of visitors, number and type of goods and services purchased, etc. Your trust and confidence are our highest priority. </p>

 <h4>Information that WokBuy.com collects</h4>
 <p>When you use our Site, we collect and store your personal information. We gather your personal information in order to record, support and facilitate your participation in the activities you select, track your preferences, to provide you with a customized Site experience, to notify you of any updated information and new activities and other related functions offered by WokBuy.com, keep you informed about latest content available on the Site, special offers, and other products and services of WokBuy, to assist you with customer service or technical support issues, to follow up with you after your visit, to otherwise support your relationship with WokBuy or to prevent fraud and unlawful use. For the aforesaid purpose, we only collect such personal information that we consider relevant to understand you or your interests.</p>
 <p>In general, you can visit the Site without having to provide your personal information during which time you remain anonymous and at no time can we identify you unless you have an account on the Site and log on with your user name and password. Once you provide your personal information, you are no more anonymous to us. To fully use our Site, you will need to register using our online registration form, where you may be required to provide us with your name, date of birth, contact number, email id, user id, password, residence / place of business information, billing information, shipping information, bank account details and other personal information as indicated on the forms throughout the Site. Further the fields are marked as mandatory or optional. You always have the option to not provide information by choosing not to use a particular service or feature on the Site. You may provide us with your WokBuy.com registered user ID. We may automatically track certain information about you based upon your behavior on our site. We use this information to analyze trends, administer the site, track a user’s movement and gather broad demographic information, to better understand, protect and serve our users. This information is compiled and analyzed on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our site or not), which URL you next go to (whether this URL is on our site or not), your computer browser information, and your IP address.</p>
 <p>We use data collection devices such as "cookies" on certain pages of the Site to help analyze our web page flow, measure promotional effectiveness, and promote trust and safety. "Cookies" are small files which identify your computer to our server as a unique user when you visit certain pages on the Site and they are stored by your Internet browser on your computer's hard drive. We offer certain features that are only available through the use of a "cookie". We also use cookies to allow you to enter your password less frequently during a session. Cookies can also help us provide information that is targeted to your interests. Most cookies are "session cookies," meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline our cookies if your browser permits, although in that case you may not be able to use full functionality of the Site. We only use cookies for your convenience in using the Site and not for obtaining or using any other information about you. We do not control the use of cookies by third parties. </p>
 <p>If you choose to buy or sell on the Site, we collect information about your buying and selling behavior.</p>
 <p>If you are a seller, we also collect some additional information, such as a billing address, banking information other payment instrument details and tracking information from cheques or money orders.</p>
 <p>If you choose to post messages on our message boards, chat rooms or other message areas or leave feedback for other users, we retain this information as necessary to resolve disputes, provide customer support and troubleshoot problems as permitted by law.</p>
 <p>If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on the Site, we may collect such information into a file specific to you.</p>
 <p>If you register for the Site on another web site or use a web site providing a service for WokBuy or a web site that helps facilitates your activity on the Site, that web site may provide personal information about you and your transactions back to us.</p>

 <h4>Our use of your information</h4>
 <p>We use your personal information to facilitate the services you request. We do not sell, rent, trade or exchange any personally-identifying information of our Users. We may provide your collected information to our affiliates and service providers under contract (such as customer care, data analytics) to support the operation of the Website and our services. To the extent we use your personal information to market to you, we will provide you the ability to opt-out of such uses. We use your personal information to: resolve disputes; troubleshoot problems; help promote safe trading; collect fees owed; measure consumer interest in the services provided by us, inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce our User Agreement, and in general to improve the user experience and make it comparable to other e-commerce websites; and as otherwise described to you at the time of collection.  In our efforts to continually improve our product and service offerings, we collect and analyze demographic, profile and usage data about our users' activity on our Site.</p>
 <p>We use your personal information to improve our platform, improve the Site's content and product offerings, prevent or detect fraud or abuses of our website and tailor it to meet your needs, so as to provide you with a smooth, efficient, safe and customized experience while using the Site.</p>
 <p>We may also use your personal information to display contents and services that are targeted to your interests. By accepting the User Agreement and Privacy Policy, you expressly agree to receive this information. If you do not wish to receive these communications, we encourage you to opt out of the receipt of certain communications in your profile under My Account or by clicking unsubscribe any email communication. You may make changes to your profile at any time.</p>

 <h4>Our Disclosure of your information</h4>
 <p>Your personal information is an important part of our business and we are not in the business of selling it to others. WokBuy.com shares your personal information only to categories of persons that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy as more particularly described below:</p>

 <h5>Advertisements</h5>
 <p>A. Where a user enters information on any form of an advertiser, the information is simultaneously collected by WokBuy.com and the advertiser. The information is used by WokBuy.com in accordance with the terms of this privacy policy and is used by the advertiser as per the advertiser’s prevalent privacy policies. Since we do not control the privacy practices of these advertisers, you should evaluate their practices before deciding to provide the said information.</p>
 <p>B. WokBuy.com may also use personally identifiable information in an aggregated form and disclose to advertisers and other third parties for other marketing and promotional purposes.</p>

 <h5>Classifieds Listings</h5>
 <p>When a user lists a classified advertisement, and the advertisement receives an expression of interest by the interested user, the interested user will be provided the contact information of the user listing the advertisement as provided in the user's registration form.</p>

 <h5>Items and Services offered on the Site by third parties</h5>
 <p>There are certain items and services for which third parties request for information to perform services on our behalf. (example: an image/picture for a customized mug/t-shirt). The information provided by the user for such purposes is simultaneously collected by WokBuy.com and the respective third party. This information is utilized by the third party in accordance with its privacy policy and the terms of the offer. Because we do not control the privacy practices of these third parties, you should evaluate their practices before deciding to use their services.</p>

 <h5>Internal Service Providers</h5>
 <p>We may employ third parties services to facilitate or outsource one or more aspects of the business, product and service operations that we provide to you on the Site (e.g., search technology, discussion boards, bill collection, affiliate and rewards programs, co-branded credit cards) and therefore we may provide some of your personal information to these internal service providers. These internal service providers' are subject to confidentiality agreements with us and other legal restrictions that prohibit their use of your personal information for any other purpose except to facilitate the specific outsourced service.. In the event of your direct involvement with the internal service provider, any additional information disclosed by you to them shall be subject to internal service provider’s own applicable privacy policy and the WokBuy.com shall not be responsible for the same.</p>

 <h5>Other Corporate Entities</h5>
 <p>We share much of our data, including personal information about you, with our parent, affiliates, subsidiaries, and joint ventures that are committed to serving your online trading needs and related services, throughout the world. To the extent that these entities have access to your personal information, they remain bound by the existing Privacy Policy. As we continue to develop our business, we might sell or buy stores, subsidiaries or business units. In such transactions, customer’s personal information generally is one of the transferred business assets but remains subject to the promises made in any pre-existing Privacy Policy. </p>

 <h5>Legal Requests</h5>
 <p>We cooperate with law enforcement and regulatory inquiries, as well as other third parties to enforce laws, such as: intellectual property rights, fraud and other rights, to help protect you and the community from bad actors. Therefore, in response to a verified request by law enforcement or other government officials relating to a criminal investigation or alleged illegal activity, we may (and you authorize us to) disclose  some of your personal information as is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.</p>

 <h5>Your use of other users' information</h5>
 <p>In order to facilitate interaction among all WokBuy.com members (buyers, sellers, services providers such as payment gateway and 3PLs, our Site allows you to access other users' contact information. Further, as a seller you will be sent via email the WokBuy.com registered user ID email address and other information, and as a winning buyer you will be sent via email the WokBuy.com registered user ID email address and other information of the seller. By entering into our User Agreement, you agree that, with respect to other user's personally identifiable information that you obtain through the Site or through a WokBuy.com-related communication or WokBuy-facilitated transaction, WokBuy.com hereby grants to you a license to use such information only for:</p>
 <p>(a). WokBuy.-related communications that are not unsolicited commercial messages,
(b). using co-branded services offered through WokBuy.com (e.g. insurance, shipping and fraud complaints), and
(c). any other purpose that such user expressly opts into after adequate disclosure of the purpose(s).</p>

 <p>In all cases, you must give users an opportunity to remove themselves from your database and a chance to review what information you have collected about them. In addition, under no circumstances, except as defined in this Section, can you disclose personally identifiable information about another user to any third party without our consent and the consent of such other user after adequate disclosure.</p>

 <p>WokBuy.com and our users do not tolerate spam. Therefore, without limiting the foregoing, you are not licensed to add a WokBuy.com user-even a user who has purchased an item from you-to your mail list (email or physical mail) without their express consent after adequate disclosure.</p>

 <h4>What about children's privacy?</h4>
 <p>Use of WokBuy.com is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are under the age of 18, you cannot buy or sell any items on the Site. If you wish to purchase or sell an item on the Site such purchase or sale may be made by your legal guardian or parents who have registered as users of the Site. </p>

 <h4>Access or change your personally identifiable information </h4>
 <p>To protect your privacy and security, we will verify your identity before granting access or making changes to your personally identifying information. If you have registered your profile on WokBuy.com, your registered user ID and Password are required in order to access your profile information.</p>

 <h4>Security</h4>
 <p>When you place orders or access your account information, we offer the use of a secure server. The secure server software (SSL) encrypts all information you put in before it is sent to us. Once your information is in our possession we adhere to strict security guidelines in compliance with the (Indian) Information Technology Act, 2000, protecting it against unauthorized access.</p>

 <h4>Your Consent</h4>
 <p>By using the Site and/ or by providing your information, you acknowledge our use of your personal information in the manner as set out in this Privacy Policy. Any changes to our privacy policy will be communicated through our Web site at least 10 days in advance of implementation. Name and address of the entity collecting and retaining your information shall be the contracting entity stated in the WokBuy.com User Agreement.</p>

 <h4>Grievance Officer:</h4>
 <p>In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are published on the Site in User Agreement.</p>
      </div>